### ISSUE TITLE
Product thumbnail not being generated until page refresh

### ISSUE THREAD

**Issue by jarrodpayne** [hws47a/VF_AjaxCart#2]
Can you think of any reason why the cart_sidebar is returning a thumbnail placeholder for the **action_content**. Once the page has been refreshed, the correct thumbnail is displayed. See image below.

Ajax request pulls in everything properly, except for the image thumbnail. The "Image Goes Here" is my product placeholder image set up in configuration.

![screen shot 2013-06-26 at 4 06 12 pm](https://f.cloud.github.com/assets/342623/711902/41594b92-de9c-11e2-9a3b-8aa7eafb260b.png)

After a page refresh, the thumbnail is generated fine.

![screen shot 2013-06-26 at 4 06 34 pm](https://f.cloud.github.com/assets/342623/711904/45b7c5a6-de9c-11e2-91cf-397d7716b14e.png)

**Comment by jarrodpayne** [comment]
If the configurable product has an image, it will be fed back to the AJAX request. I am still not able to get it to show the proper associated product image until after a page refresh.

**Comment by hws47a** [comment]
Didn't find any problems, cleared images cache, then added image on product page and see the image in sidebar cart

![screen shot 2014-04-19 at 22 19 34](https://cloud.githubusercontent.com/assets/604641/2749167/b178179a-c7ef-11e3-9b4d-2d2fb769faac.png)
